// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package rnv.proxies;

public class Ctx
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject ctxMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "RNV.Ctx";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Ident("Ident"),
		RoomName("RoomName"),
		Tok("Tok");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Ctx(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "RNV.Ctx"));
	}

	protected Ctx(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject ctxMendixObject)
	{
		if (ctxMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("RNV.Ctx", ctxMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a RNV.Ctx");

		this.ctxMendixObject = ctxMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Ctx.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static rnv.proxies.Ctx initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return rnv.proxies.Ctx.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static rnv.proxies.Ctx initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new rnv.proxies.Ctx(context, mendixObject);
	}

	public static rnv.proxies.Ctx load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return rnv.proxies.Ctx.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Ident
	 */
	public final java.lang.String getIdent()
	{
		return getIdent(getContext());
	}

	/**
	 * @param context
	 * @return value of Ident
	 */
	public final java.lang.String getIdent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Ident.toString());
	}

	/**
	 * Set value of Ident
	 * @param ident
	 */
	public final void setIdent(java.lang.String ident)
	{
		setIdent(getContext(), ident);
	}

	/**
	 * Set value of Ident
	 * @param context
	 * @param ident
	 */
	public final void setIdent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ident)
	{
		getMendixObject().setValue(context, MemberNames.Ident.toString(), ident);
	}

	/**
	 * @return value of RoomName
	 */
	public final java.lang.String getRoomName()
	{
		return getRoomName(getContext());
	}

	/**
	 * @param context
	 * @return value of RoomName
	 */
	public final java.lang.String getRoomName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RoomName.toString());
	}

	/**
	 * Set value of RoomName
	 * @param roomname
	 */
	public final void setRoomName(java.lang.String roomname)
	{
		setRoomName(getContext(), roomname);
	}

	/**
	 * Set value of RoomName
	 * @param context
	 * @param roomname
	 */
	public final void setRoomName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String roomname)
	{
		getMendixObject().setValue(context, MemberNames.RoomName.toString(), roomname);
	}

	/**
	 * @return value of Tok
	 */
	public final java.lang.String getTok()
	{
		return getTok(getContext());
	}

	/**
	 * @param context
	 * @return value of Tok
	 */
	public final java.lang.String getTok(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Tok.toString());
	}

	/**
	 * Set value of Tok
	 * @param tok
	 */
	public final void setTok(java.lang.String tok)
	{
		setTok(getContext(), tok);
	}

	/**
	 * Set value of Tok
	 * @param context
	 * @param tok
	 */
	public final void setTok(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tok)
	{
		getMendixObject().setValue(context, MemberNames.Tok.toString(), tok);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return ctxMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final rnv.proxies.Ctx that = (rnv.proxies.Ctx) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "RNV.Ctx";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
