export const CustomVideo={
	container:{
		backgroundColor:"#000000",
		//width:wp("100%"),
		//height:hp("100%")
	},
	callContainer:{
		//height:hp("100%"),
		//width:wp("100%"),
		backgroundColor:"#000000",
		zIndex:0,
		elevation:0
	},
		callContainerLocalVideo:{
			width:"100%",
			height:"100%",
			zIndex:0,
			elevation:0,
			backgroundColor:"#000000",
			zIndex:1,
			elevation:1
		},
		callContainerRemoteVideo:{
			width:"100%",
			height:"80%",
			backgroundColor:"#000000",
			zIndex:2,
			elevation:2
		},
	callTileContainer:{
		position:"absolute",
		bottom:"10%",
		left:0,
		height:"10%",
		//width:wp("100%"),
		backgroundColor:"#000000"
	},
		remoteTileGrid:{
			flex:1,
			flexDirection:"row",
			height:"100%",
			width:"100%",
			backgroundColor:"#000000"
		},
			remoteTileTouchableOpacity:{
				zIndex:12,
				elevation:12
			},
				remoteTileVideo:{
					height:"100%",
					aspectRatio:1,
					backgroundColor:"#000000"
				},
	callButtonContainer:{
		position:"absolute",
		left:0,
		bottom:0,
		height:"10%",
		flexDirection:"row",
		alignItems:"center",
		justifyContent:"space-evenly",
		backgroundColor:"#FFFFFF"
	},
		callButtonContainerButton:{
			width:"33.33%",
			height:"100%",
			//backgroundColor:"#000000",
			justifyContent:"center",
			alignItems:"center",
		},
			callButtonContainerButtonText:{
				color:"#FFFFFF",
				fontSize:16
			},
			callButtonContainerButtonImage:{
				width:"100%",
				height:"100%"
			}
};

