// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package rnv.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the RNV module
	public static rnv.proxies.Ctx ds_atok(IContext context, rnv.proxies.Ctx _obj_ctx)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("obj_ctx", _obj_ctx == null ? null : _obj_ctx.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("RNV.ds_atok").withParams(params).execute(context);
		return result == null ? null : rnv.proxies.Ctx.initialize(context, result);
	}
	public static rnv.proxies.Ctx ds_ctx(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("RNV.ds_ctx").withParams(params).execute(context);
		return result == null ? null : rnv.proxies.Ctx.initialize(context, result);
	}
}